### ISSUE TITLE
New color theme

### ISSUE THREAD

**Issue by yuriy1337** [yuriy1337/Lunch-Randomizer#16] opened 2011-04-13 01:55 UTC
Navy blue and grey is not the best combination of colors. Maybe we can use Themeroller to get a new theme: http://jqueryui.com/themeroller/

**Comment by tomarra** [comment] 2011-04-13 01:59
The grey and blue was added just we had something. I agree we need a theme. Not sure if themeroller is the way to go but since we already have jQueryUI in the project it may be the easy way out. I will look into it and report back.

**Comment by tomarra** [comment] 2011-04-13 02:29
Themeroller does a good job of themeing the jQuery components but we would still have to try and match that for the rest of the site by hand. Going to look around and see if there are any other easy options out there before investing more time here.

**Comment by yuriy1337** [comment] 2011-04-13 02:41
While it does provide theming for jQuery components, it can also be used for others like Highlight / Error, Button, etc... If you find anything else, report back. We'll choose whatever is the best.

**Comment by yuriy1337** [comment] 2011-04-13 02:45
Since RoR has great gems and plugins... A quick google search showed: http://www.gaugeus.com/ramblings/2007/11/4/adding-theme-support-to-a-ruby-on-rails-application

Don't have to use this, but maybe another gem is what we need.

**Comment by yuriy1337** [comment] 2011-04-14 01:18
Also check this out http://teachmetocode.com/screencasts/styleize-your-rails-app-with-themes/
that looks good or this:
http://gravityblast.com/2009/07/30/2-minutes-admin-layout-with-rails-and-the-web-app-theme-generator/

**Comment by tomarra** [comment] 2011-04-14 02:21
I really like the second link. Having issues with my local environment though when trying to install the plugin :(

**Comment by yuriy1337** [comment] 2011-04-14 02:27
I just tried installing it and it installed fine. How are you doing it?

just add:
gem 'web-app-theme', '>= 0.6.2'
to the Gemfile
and then open command line (or terminal) and run
bundle install

**Comment by tomarra** [comment] 2011-04-14 02:30
I was trying to install the plugin, then saw there was a gem, Doh!

**Comment by yuriy1337** [comment] 2011-04-14 02:31
oh haha, this has newer instructions https://github.com/pilu/web-app-theme

**Comment by tomarra** [comment] 2011-04-14 03:07
A overall theme is checked in. This should make it easier to change the entire site later on. Not going to close this until we make sure regression testing passes.

**Comment by yuriy1337** [comment] 2011-04-14 03:11
I get error when starting "Could not find mysql2-0.2.7 in any of the sources"

**Comment by tomarra** [comment] 2011-04-14 03:13
Adam added mysql2 to the gemfile. Run bundler.

**Comment by yuriy1337** [comment] 2011-04-14 03:22
Did he fork of yours? I did not see a pull request from Adam.

**Comment by tomarra** [comment] 2011-04-14 03:24
You did it earlier. I pulled the change down from your stream.

**Comment by yuriy1337** [comment] 2011-04-14 03:26
Eh something weird happened, I think, but whatever. Mysql gem failed building :(

**Comment by tomarra** [comment] 2011-04-14 03:36
you should have to worry about mysql as its only used in production. sqlite should be used in development and test as the mysql2 gem does not work well on windows.

**Comment by yuriy1337** [comment] 2011-04-14 04:06
Yes, but that means i have to edit my gemfile and i might commit it accidentally. I am still having problems. My sqlite3 db is created but it says it cannot find the user table.

**Comment by yuriy1337** [comment] 2011-04-17 01:00
I think this can be closed, if you agree.

**Comment by tomarra** [comment] 2011-04-17 01:12
I want to clean up the views to use the strings files but that can be done later on. Closing this issue.

**Closed as completed by tomarra** 2011-04-17 01:12 UTC
